name: Validacion de Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v4

      - name: Listar archivos del repo
        run: |
          pwd
          ls -la
          ls -la server || echo "No existe carpeta server"

      - name: Login a DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Ejecutar Docker Bake con salida detallada
        run: |
          docker buildx bake --file docker-bake.hcl --progress=plain
